project_name: determined-agent

snapshot:
  name_template: "{{ .Env.VERSION }}"

builds:
  - main: ./cmd/determined-agent
    goos:
      - linux
    goarch:
      - amd64

dockers:
  # amd64
  - goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --builder=buildx-build
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64"
    extra_files:
      - packaging/entrypoint.sh
      - packaging/LICENSE

docker_manifests:
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64"
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.ShortCommit}}"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64"
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.Env.VERSION}}"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64"
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:latest"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64"
